name: Publish to CodeArtifact

on:
  push:
    branches: [ main ]  # fires after merging a PR into main
  workflow_dispatch:     # allows manual triggering

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-central-1"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Configure AWS Credentials to allow publishing to CodeArtifact
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::051826707296:role/GithubActionsDevelopment
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4. Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # (Optional) 5. Install dependencies
      # If you have any runtime or dev dependencies needed for building,
      # tests, or linting, do that here:
      - name: Install project dependencies
        run: poetry install

      # 6. Call the Makefile target that does it all
      - name: Make Publish
        run: make publish
